<?php

/**
 * Implementation of hook_menu().
 */
function aksearch_publications_menu() {
	$items['admin/config/aksearch_publications'] = array(
			'title' => 'Agroknow Search configuration',
			'description' => 'Specify options for Agroknow Publications Search module.',
			'position' => 'right',
			'weight' => -5,
			'page callback' => 'system_admin_menu_block_page',
			'access arguments' => array('administer site configuration'),
			'file' => 'system.admin.inc',
			'file path' => drupal_get_path('module', 'system'),
	);
	$items['admin/config/aksearch_publications/settings'] = array(
			'title' => 'Agroknow Publications Search settings',
			'description' => 'Change the Agroknow Publications Search behaves.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('aksearch_publications_admin_settings'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'aksearch_publications.admin.inc',
	);
	$items['akconf'] = array(
			'page callback' => 'akpubnode_config',
			'page arguments' => array(1),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	return $items;
}

/**
 * Menu callback for aksearch_publications node configuration
 */
function akpubnode_config($n){
	$result = db_query('SELECT conf FROM {aksearch_publications_conf} WHERE nid = :nid LIMIT 1', array(':nid' => $n));
	echo $result->fetchField();
	drupal_exit();
}

/**
* Implements hook_node_info()
*/
function aksearch_publications_node_info() {
return array(
	'aksearch_publications' => array(
	'name' => t('Agroknow Publications Search'),
	'base' => 'aksearch_publications',
	'description' => t('Use this content type to create a Agroknow Publications Search page.'),
	'has_title' => TRUE,
	'title_label' => t('Title'),
	'help' => t('Enter the title'),
	),
);
}

/**
* Implements hook_form()
*/
function aksearch_publications_form($node, $form_state) {
return node_content_form($node, $form_state);
}

/**
 * Implements hook_insert()
 */
function aksearch_publications_insert($node){

$cf = file_get_contents(drupal_get_path('module','aksearch_publications').'/default/config/conf.json');
$r = db_insert('aksearch_publications_conf')
->fields(array(
'nid' => $node->nid,
'conf' => $cf,
))
->execute();
	
	
}

/**
* Implements hook_view()
*/
function aksearch_publications_view($node){
	$issearch = $node->nid == variable_get('aksearch_publications_spage',0) ? true : false ;

		$node->content['body'] = array(
			'#markup' => theme('aksearch_publications', 
				array('cont'=> $node->body,'search' => $issearch , 'nif' => $node->nid)
			),
			'#weight' => 1,
			);
	return $node;

}

/**
* Implements hook_theme()
*/
function aksearch_publications_theme() {
return array(
    'aksearch_publications' => array(
      'variables' => array('cont'=> '','search' => true , 'nif' => 0),
      'template' => 'aksearch_publications',
    ),
	);
}
